{% set name = "pyRingGW" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyRingGW-{{ version }}.tar.gz
  sha256: 8bce5ddbec098e63e5386d5ab27e21b377cab9a40cd87899fad587851a0b16de

build:
  skip: true  # [win]
  entry_points:
    - pyRing = pyRing.pyRing:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - cython
    - numpy
    - pip
  run:
    - python
    - corner
    - cpnest
    - cython
    - gwpy
    - h5py
    - lalsuite
    - matplotlib-base
    - pesummary
    - seaborn-base
    - scipy
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pyRing
  commands:
    - pip check
    - pyRing --help
  requires:
    - pip

about:
  home: https://git.ligo.org/lscsoft/pyring
  summary: 'pyRing: Black hole ringdown data-analysis in time-domain'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - GCarullo
