{% set name = "pyRingGW" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyRingGW-{{ version }}.tar.gz
  sha256: 6121d5386a39b51eab73bc244282d9a3e0e59d441caa35edbec037d285b0f98d

build:
  skip: true  # [win]
  entry_points:
    - pyRing = pyRing.pyRing:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython
    - numpy
    - pip
  run:
    - python
    - corner
    - cpnest
    - cython
    - gwpy
    - h5py
    - lalsuite
    - matplotlib-base
    - pesummary
    - raynest
    - seaborn-base
    - scipy
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pyRing
  commands:
    - pip check
    - pyRing --help
  requires:
    - pip

about:
  home: https://git.ligo.org/lscsoft/pyring
  summary: 'pyRing: Black hole ringdown data-analysis in time-domain'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - GCarullo
