{% set name = "pyRingGW" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyRingGW-{{ version }}.tar.gz
  sha256: f354b2ee1104d09091c1ea1ca7f1d05ad08aa8f0fd1c09bc0a8605917a6b5ad6

build:
  skip: true  # [py<36]
  skip: true  # [win]
  entry_points:
    - pyRing = pyRing.pyRing:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython
    - numpy
    - pip
  run:
    - python
    - corner
    - cpnest
    - cython
    - gwpy
    - h5py
    - lalsuite
    - matplotlib-base
    - pesummary
    - seaborn
    - scipy
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pyRing
  commands:
    - pip check
    - pyRing --help
  requires:
    - pip

about:
  home: https://git.ligo.org/lscsoft/pyring
  summary: 'pyRing: Black hole ringdown data-analysis in time-domain'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - GCarullo
