schema_version: 1

context:
  name: pyRingGW
  version: "2.9.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | lower }}-${{ version }}.tar.gz
  sha256: 4538680e023a29358884a99103e6a6cc45023a12ec7f9b6e9ca8eff387dcf4e2

build:
  number: 0
  python:
    entry_points:
      - pyRing = pyRing.pyRing:main
  script: ${{ PYTHON }} -m pip install . -vv
  skip:
    - win

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - cython
        - numpy
        - python
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
  run:
    - corner
    - cpnest
    - cython
    - gwpy
    - h5py
    - lalsuite
    - matplotlib-base
    - pesummary
    - python
    - scipy
    - seaborn-base

tests:
  - requirements:
      run:
        - pip
        - pytest
    script:
      # Check metadata
      - python -m pip check
      - python -m pip show pyringgw
      # Run test suite
      - python -m pytest --pyargs -ra -v pyRing.tests
      # Check entry point
      - pyRing --help

about:
  summary: "pyRing: Black hole ringdown data-analysis in time-domain"
  homepage: https://git.ligo.org/lscsoft/pyring
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - duncanmmacleod
    - GCarullo
